---
- name: "Set system boot up chime volume to {{ macos_settings.boot_volume }}"
  become: true
  command: "nvram SystemAudioVolume={{ macos_settings.boot_volume }}"
  when: macos_settings.boot_volume != false

- name: Restart automatically if the computer freezes
  become: true
  command: "systemsetup -setrestartfreeze on"
  when: macos_settings.restart_on_freeze

- name: Do NOT restart automatically if the computer freezes
  become: true
  command: "systemsetup -setrestartfreeze off"
  when: not macos_settings.restart_on_freeze

- name: "Enable the MacBook Air SuperDrive on any Mac"
  become: true
  command: 'nvram boot-args="mbasd=1"'
  when: macos_settings.superdrive

- name: "Disable the MacBook Air SuperDrive on any Mac"
  become: true
  command: 'nvram boot-args="mbasd=0"'
  when: macos_settings.superdrive