---
- name: Get old pmset 'sudden motion sensor' value
  shell: "pmset -g | grep \"^\\s*sms.*\" | awk -F \" \" '{ print $2 }'"
  register: pmset_old
  changed_when: false

- name: "Set sudden motion sensor mode to {{ macos_settings.sudden_motion_sensor }}"
  become: true
  command: "pmset -a sms {{ macos_settings.sudden_motion_sensor | ternary(1, 0) }}"
  when: "macos_settings.sudden_motion_sensor and (pmset_old.stdout | string ) != (macos_settings.sudden_motion_sensor | ternary(1, 0) | string ) and 'sms' in pmset_cap.stdout"
