---
- name: "Start iTunes listening to the keyboard media keys"
  become: true
  shell: "launchctl load -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null"
  when: macos_settings.itunes_media_keys

- name: "Stop iTunes listening to the keyboard media keys"
  become: true
  shell: "launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null"
  when: not macos_settings.itunes_media_keys
