---
- debug:
    msg: "{{ vars[(role_path | basename).split('.')[-1].replace('-','_').replace('ansible_','')] }}"
  when: DEBUG | d() | bool

- include_tasks: boot.yml
- include_tasks: hardware.yml
- include_tasks: spotlight.yml
- include_tasks: itunes.yml
