---
- debug:
    msg: "{{ vars[(role_path | basename).split('.')[-1].replace('-','_').replace('ansible_','')] }}"
  when: DEBUG | d() | bool

- include: boot.yml
- include: hardware.yml
- include: spotlight.yml
- include: itunes.yml
