---
- name: "Disable Notification Center and remove the menu bar icon"
  become: true
  command: "launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null"
  when: not macos_settings.notification_center

- name: "Enable Notification Center and add the menu bar icon"
  become: true
  command: "launchctl load -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null"
  when: macos_settings.notification_center