---
- name: "Set Spotlight tray-icon mode to {{ macos_settings.spotlight_hide_tray_icon | ternary('0600', '0755') }}"
  become: true
  file:
    path: "/System/Library/CoreServices/Search.bundle/Contents/MacOS/Search"
    mode: "{{ macos_settings.spotlight_hide_tray_icon | ternary('0600', '0755') }}"
  when: macos_settings.spotlight_hide_tray_icon

- name: "Load new settings before rebuilding the index"
  become: true
  command: "killall mds > /dev/null 2>&1"
  when: macos_settings.spotlight_reindex

- name: "Enable indexing for the main volume"
  become: true
  command: "mdutil -i on / > /dev/null"
  when: macos_settings.spotlight_reindex

- name: "Trigger rebuild the index from scratch"
  become: true
  command: "mdutil -E / > /dev/null"
  when: macos_settings.spotlight_reindex
